<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\xwt.snk</AssemblyOriginatorKeyFile>
    <AssemblyTitle>Xwt.Gtk.Windows</AssemblyTitle>
    <Product>Xwt UI Framework</Product>
    <Description>
Xwt is a cross-platform UI toolkit for creating desktop applications with .NET and Mono.

This package contains the GTK toolkit backend for Xwt based applications targeting GTK2 on Windows.

Xwt.Gtk requires gtk-sharp (https://github.com/mono/gtk-sharp/). The Windows installation package can be obtained from http://www.monodevelop.com/download/#win.
		</Description>
    <Copyright>Xamarin, Inc (http://www.xamarin.com)</Copyright>
    <Version>0.1.0.0-prerelease</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <LangVersion>6</LangVersion>
    <ConsolePause>false</ConsolePause>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Lluis Sanchez</Authors>
    <PackageLicenseUrl>https://raw.githubusercontent.com/mono/xwt/master/LICENSE.txt</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/mono/xwt/</PackageProjectUrl>
    <PackageTags>xwt cross platform gui ui toolkit framework desktop gtk gtk2</PackageTags>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="gdk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f, processorArchitecture=MSIL" />
    <Reference Include="glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f, processorArchitecture=MSIL" />
    <Reference Include="gtk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f, processorArchitecture=MSIL" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="atk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="PresentationFramework" />
    <Reference Include="WindowsBase" />
    <Reference Include="WindowsFormsIntegration" />
    <Reference Include="PresentationCore" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Xwt.WPF\Xwt.WPFBackend.Interop\IDocHostUIHandler.cs" Link="IDocHostUIHandler.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xwt.Gtk\Xwt.Gtk.csproj" />
    <ProjectReference Include="..\Xwt\Xwt.csproj" />
  </ItemGroup>
</Project>