<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProductVersion>8.0.30703</ProductVersion>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\xwt.snk</AssemblyOriginatorKeyFile>
    <AssemblyTitle>Xwt.Gtk.Mac</AssemblyTitle>
    <Product>Xwt UI Framework</Product>
    <Description>
Xwt is a cross-platform UI toolkit for creating desktop applications with .NET and Mono.

This package contains the GTK toolkit backend for Xwt based applications targeting GTK2 on Mac.

Xwt.Gtk requires gtk-sharp (https://github.com/mono/gtk-sharp/). The Windows installation package can be obtained from http://www.monodevelop.com/download/#win.
		</Description>
    <Copyright>Xamarin, Inc (http://www.xamarin.com)</Copyright>
    <Version>0.1.0.0-prerelease</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <LangVersion>6</LangVersion>
    <ConsolePause>false</ConsolePause>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Lluis Sanchez</Authors>
    <PackageLicenseUrl>https://raw.githubusercontent.com/mono/xwt/master/LICENSE.txt</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/mono/xwt/</PackageProjectUrl>
    <PackageTags>xwt cross platform gui ui toolkit framework desktop gtk gtk2</PackageTags>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup>
    <XamMacPath>\Library\Frameworks\Xamarin.Mac.framework\Versions\Current\lib\x86_64\full\Xamarin.Mac.dll</XamMacPath>
    <XamMacPath Condition="Exists('$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Xamarin.Mac.dll')">$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Xamarin.Mac.dll</XamMacPath>
    <XamMacPath Condition="Exists('$(MSBuildProgramFiles32)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Xamarin.Mac.dll')">$(MSBuildProgramFiles32)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Xamarin.Mac.dll</XamMacPath>
    <XamMacPath Condition="Exists('$(MSBuildToolsPath)\..\..\..\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Xamarin.Mac.dll')">$(MSBuildToolsPath)\..\..\..\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.Mac\v2.0\Xamarin.Mac.dll</XamMacPath>
  </PropertyGroup>
  <Import Project="..\BuildHelpers.targets" />
  <ItemGroup>
    <Reference Include="gtk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="atk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="gdk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="Xamarin.Mac">
      <HintPath>$(XamMacPath)</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Xwt.XamMac\Xwt.Mac\NSApplicationInitializer.cs" Link="NSApplicationInitializer.cs" />
    <Compile Include="..\Xwt.XamMac\Xwt.Mac\AccerssibilityHelper.cs" Link="AccerssibilityHelper.cs" />
    <Compile Include="..\Xwt.XamMac\Xwt.Mac\FileDialogBackend.cs" Link="FileDialogBackend.cs" />
    <Compile Include="..\Xwt.XamMac\Xwt.Mac\SelectFolderDialogBackend.cs" Link="SelectFolderDialogBackend.cs" />
    <Compile Include="..\Xwt.XamMac\Xwt.Mac\OpenFileDialogBackend.cs" Link="OpenFileDialogBackend.cs" />
    <Compile Include="..\Xwt.XamMac\Xwt.Mac\SaveFileDialogBackend.cs" Link="SaveFileDialogBackend.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xwt.Gtk\Xwt.Gtk.csproj" />
    <ProjectReference Include="..\Xwt\Xwt.csproj" />
  </ItemGroup>
</Project>