<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Xwt.GtkBackend</RootNamespace>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\xwt.snk</AssemblyOriginatorKeyFile>
    <ProductVersion>8.0.30703</ProductVersion>
    <AssemblyTitle>Xwt.Gtk</AssemblyTitle>
    <Product>Xwt UI Framework</Product>
    <Description>Gtk Toolkit for the Xwt UI Framework</Description>
    <Copyright>Xamarin, Inc (http://www.xamarin.com)</Copyright>
    <Version>0.1.0.0-prerelease</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>6</LangVersion>
    <ConsolePause>False</ConsolePause>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="gtk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="atk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="gdk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
    <Reference Include="Mono.Cairo" />
    <Reference Include="pango-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Xwt.GtkBackend\ScrollAdjustmentBackend.cs">
      <Gettext-ScanForTranslations>False</Gettext-ScanForTranslations>
    </Compile>
    <Compile Update="Xwt.GtkBackend\ScrollControlBackend.cs">
      <Gettext-ScanForTranslations>False</Gettext-ScanForTranslations>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xwt\Xwt.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="icons\searchbox-clear-16.png">
      <LogicalName>searchbox-clear-16.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-clear-16%402x.png">
      <LogicalName>searchbox-clear-16@2x.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-clear-16~dark.png">
      <LogicalName>searchbox-clear-16~dark.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-clear-16~dark%402x.png">
      <LogicalName>searchbox-clear-16~dark@2x.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-search-16%402x.png">
      <LogicalName>searchbox-search-16@2x.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-search-16.png">
      <LogicalName>searchbox-search-16.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-search-16~dark%402x.png">
      <LogicalName>searchbox-search-16~dark@2x.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icons\searchbox-search-16~dark.png">
      <LogicalName>searchbox-search-16~dark.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AssemblyInfo.Gtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\BoxBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\ButtonBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\CanvasBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\Gtk3DrawingArea.cs" />
    <Compile Remove="Xwt.GtkBackend\Gtk3Extensions.cs" />
    <Compile Remove="Xwt.GtkBackend\Gtk3FontChooserDialog.cs" />
    <Compile Remove="Xwt.GtkBackend\Gtk3PopoverWindow.cs" />
    <Compile Remove="Xwt.GtkBackend\Gtk3ViewPort.cs" />
    <Compile Remove="Xwt.GtkBackend\HeaderBoxGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\LabelBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\PanedBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\PasswordEntryBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\SearchTextEntryBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\SpinButtonBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\TextEntryBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend\WidgetBackendGtk3.cs" />
    <Compile Remove="Xwt.GtkBackend.CellViews\Gtk3CellRendererCustom.cs" />
  </ItemGroup>
</Project>